### ISSUE TITLE
Docs generation fails in template

### ISSUE THREAD

**Issue by NatElkins** [ionide/Waypoint#23]
**Describe the bug**

When I install the Waypoint template and create a new instance of it using `dotnet new Waypoint`, the Docs generation target will fail.

**To Reproduce**
1. `dotnet new -i Waypoint`
2. `mkdir WaypointTest`
3. `cd WaypointTest`
4. `dotnet new Waypoint`
5. `dotnet tool restore`
6. `dotnet fake build -t Docs`

**Expected behaviour**
Docs generation succeeds.

**Screenshots**
![image](https://user-images.githubusercontent.com/1795462/83336948-707fdf80-a285-11ea-84b5-c5dc7a9c24fe.png)

**Environment (please complete the following information):**
 - OS: Ubutunu 20.04
 - Ionide version: 4.11.1
 - VSCode version: 1.45.1
 - dotnet SDK version: 3.1.201
 - mono / .Net Framework version: N/A

**Comment by Krzysztof-Cieslak** [comment]
This may be fixed in unreleased patch from @NicoVIII - https://github.com/ionide/Waypoint/commit/1458c9c78a16812be8a104aba8ce31b206710a59

**Comment by NicoVIII** [comment]
Yes, I think that was the error I got.

**Comment by NatElkins** [comment]
Yes that fixed it!  I'll close the issue.
