### ISSUE TITLE
Clarification of How to Build application instructions

### ISSUE THREAD

**Issue by jbeeko** [ionide/Waypoint#4]
Step 2. says:
>2. Run dotnet tool install to install all developer tools required to build the project

What does this mean? Running `dotnet tool install` does nothing. Should this read 
>2. Run dotnet tool install to install any additional developer tools required to build the project

**Comment by zaymonoid** [comment]
Should it actually be `dotnet tool restore`?

**Comment by Krzysztof-Cieslak** [comment]
Yes, it should be `dotnet tool restore` 😅
